name: Atualizar Submodule Automático (PR)
on:
  repository_dispatch:
    types: [atualizou-componente]

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o projeto
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          submodules: recursive
          fetch-depth: 0

      - name: Atualizar submodules para a última versão
        run: git submodule update --remote --recursive

      - name: Criar Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "chore(deps): atualiza design-system-components"
          branch: "update-design-system"
          delete-branch: true
          title: "🔄 Atualização: design-system-components"
          body: |
            O repositório `design-system-components` teve alterações na main.
            
            Esta PR atualiza a referência do submódulo para a última versão disponível.
            
            **Por favor, verifique se a build e os testes estão passando antes de fazer o merge.**
          labels: automação, atualização
